### ISSUE TITLE
KeyPropertiesField data property is a Model object 

### ISSUE THREAD

**Issue by shday** [wtforms/wtforms-appengine#1]
Hi,

Not sure if this is an issue or intended behavior.  It seems that KeyPropertiesField should be converting form data into Key objects (not Model objects). This is also what the docstring of ModelConverter indicates. 

In any case, it would be nice if this were an option at least. I will probably fork and work on it myself, but I was hoping to get your thoughts first.

Thanks,

Stephen

**Comment by dhstack** [comment]
@shday I was wondering the same thing - did you ever get it to do the expected behavior of only converting to a Key object (and not a Model object)?

**Comment by shday** [comment]
@dhstack I forked the project and changed the behavior to what it should be: https://github.com/shday/wtforms-appengine.

But it's been a while since I used the library...

**Comment by dhstack** [comment]
@shday Thanks for the link - I was able to fix my issue (form with radio buttons derived from a KeyProperty field in ndb) after applying it. Thank you.

You should submit a pull request to get it included in the master branch.
