### ISSUE TITLE
Use verbose_name in field labels

### ISSUE THREAD

**Issue by adsahay** [wtforms/wtforms-appengine#2]
In ndb.py:

```
'label': prop._code_name.replace('_', ' ').title(),
```
should be modified to use [verbose_name][1] from the ndb model property where available.

```
'label': prop._verbose_name or prop._code_name.replace('_', ' ').title()
```

[1]: https://developers.google.com/appengine/docs/python/ndb/properties

**Comment by mikelambert** [comment]
Thanks for the suggestion, I'm going to merge this in now.
