### ISSUE TITLE
Model forms & ndb.KeyProperty as string

### ISSUE THREAD

**Issue by pwalsh** [wtforms/wtforms-appengine#4]
If you use strings for kind on ndb.KeyProperty, and your model is in a different module, wtforms-appengine errors when trying to create a model form, as it only looks in the current module for the class the string represents.

There is no simply solution for this, as apps using Datastore have no imposed convention for declaring models, in terms of where to declare them.

I'm suggesting the following possible solution:

Have a setting that can be accessed via a key on the environment, and this setting provides a list of strings that represent the full path to a model definition.

For example:

# accounts.py
class Account(mdb.Model):
    # etc

# shows.py
class Show(mdb.Model):
    account = db.KeyProperty(kind='Account', required=True)
    # etc

# envvar
WTFORMS_MODEL_RESOLVER = [
    'myproject.accounts.Account',
]

Now, when trying to load a model from a string, as in:

https://github.com/wtforms/wtforms-appengine/blob/master/wtforms_appengine/ndb.py#L335

A condition can be written to first (or later) check if there is a matching model in WTFORMS_MODEL_RESOLVER, and resolve with that string.

Any thoughts or suggestions?

**Comment by mikelambert** [comment]
I just created https://github.com/wtforms/wtforms-appengine/pull/16 which should fix what was described in this thread, along with a test (verified as failed before my change, and working after my change). I'm a bit reluctant to merge my own pull requests, so if anyone wants to give it a once-over, I'd appreciate it!
